### ISSUE TITLE
-WEBKIT-USER-SELECT:NONE导致输入框无法输入

### ISSUE THREAD

**Issue by mkmg88** [mkmg88/study#9]
最近在webview中写页面的时候发现个别Android机型（Google  Nexus，Android 4.2.2）输入框无法输入（但是键盘可以弹起，所以不是网上所说webView.requestFocus(View.FOCUS_DOWN);的问题），经过试错发现是-webkit-user-select:none;所导致的原因。

当然如果你确实需要这个-webkit-user-select这个属性，也可以这样写css代码：

```css
*:not(input,textarea) {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
}
```
